---
- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /opt/k3s-setup/install_k3s.sh
    mode: '0755'

- name: Install k3s agent
  shell: |-
    K3S_URL="https://{{ hostvars[groups['k3s_masters'].keys()|list|first }}:6443" K3S_TOKEN='{{ k3s_token }}' INSTALL_K3S_VERSION={{ k3s_version }} sh /opt/k3s-setup/install_k3s.sh
  args:
    creates: /etc/rancher/k3s/k3s.yaml
