apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Flux components
- flux-system/gotk-components.yaml

# Infrastructure
- infrastructure
- infrastructure/cert-manager
- infrastructure/cert-manager-resources

# Monitoring
- monitoring

# Apps
- apps/jellyfin # <-- point to folder, not the kustomization.yaml file

# Secrets
- secrets
