apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Flux components
- flux-system/flux-system-crds.yaml
- flux-system/gotk-components.yaml

# Infrastructure
- infrastructure

# Monitoring
- monitoring

# Apps
- apps/jellyfin # <-- point to folder, not the kustomization.yaml file
