apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- kustomization-crds.yaml
- kustomization-cert-manager.yaml
- kustomization-cert-manager-resources.yaml
- ../infrastructure/kustomization.yaml
- ../apps/jellyfin/kustomization.yaml
- ../monitoring/kustomization.yaml
- ../secrets/kustomization.yaml
