apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux-system-crds
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
