apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterissuer-staging.yaml
- clusterissuer-production.yaml
- wildcard-certificate.yaml
dependsOn:
- name: cert-manager
  namespace: flux-system
