all:
  children:
    k3s_masters:
      hosts:
        k3s-master-1:
          ansible_host: 192.0.2.10
          ansible_user: ubuntu
    k3s_workers:
      hosts:
        worker-1:
          ansible_host: 192.0.2.11
          ansible_user: ubuntu
