apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- longhorn/namespace.yaml
- helmrepos.yaml
- traefik/helmrelease.yaml
- metal-lb/helmrelease.yaml
- longhorn/helmrelease.yaml
- jetstack-helmrepo.yaml
- reflector/helmrelease.yaml
- reflector/helmrepo.yaml
